// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8l3Nso_wO1i2eNe0Uyxd_3y5bCVrIids',
    appId: '1:988993264785:android:09491ea462c614545f7330',
    messagingSenderId: '988993264785',
    projectId: 'family-meal-planner-67475',
    storageBucket: 'family-meal-planner-67475.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYJ-JJxo4IWv-94_G43UYFL21s4FyXkBk',
    appId: '1:988993264785:web:abe5064c2c7617af5f7330',
    messagingSenderId: '988993264785',
    projectId: 'family-meal-planner-67475',
    authDomain: 'family-meal-planner-67475.firebaseapp.com',
    storageBucket: 'family-meal-planner-67475.firebasestorage.app',
    measurementId: 'G-6VDV0CJEWD',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYJ-JJxo4IWv-94_G43UYFL21s4FyXkBk',
    appId: '1:988993264785:web:08be43dcc9efa90e5f7330',
    messagingSenderId: '988993264785',
    projectId: 'family-meal-planner-67475',
    authDomain: 'family-meal-planner-67475.firebaseapp.com',
    storageBucket: 'family-meal-planner-67475.firebasestorage.app',
    measurementId: 'G-S21N071E0L',
  );
}
